app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user
pro_registration:
    path:  /register/pro
    defaults: { _controller: UserBundle:RegistrationPro:register }

student_registration:
    path:  /register/student
    defaults: { _controller: UserBundle:RegistrationStudent:register} 
admin_registration:
    path:  admin/register
    defaults: { _controller: UserBundle:RegistrationAdmin:register} 

collegeStudent_registration:
    path:  /register/cstudent
    defaults: { _controller: UserBundle:RegistrationCollegeStudent:register}

former_registration:
    path:  /register/former
    defaults: { _controller: UserBundle:RegistrationFormer:register}
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile 