fos_user:
    db_driver: orm
    firewall_name: main
    user_class: UserBundle\Entity\User
    service:
        user_manager: pugx_user_manager
    from_email:
        address: yassine.youns@gmail.com
        sender_name: AcaRobotics